---
# Prints the status of the pulpcore services and fails
# Designed for CI/molecule only

- block:
    - name: systemctl status pulpcore
      command: systemctl status pulpcore
    - name: journalctl -u pulpcore
      command: journalctl -u pulpcore
    - name: systemctl status pulpcore-api
      command: systemctl status pulpcore-api
    - name: journalctl -u pulpcore-api
      command: journalctl -u pulpcore-api
    - name: systemctl status pulpcore-content
      command: systemctl status pulpcore-content
    - name: journalctl -u pulpcore-content
      command: journalctl -u pulpcore-content
    - name: systemctl status pulpcore-worker@1
      command: systemctl status pulpcore-worker@1
    - name: journalctl -u pulpcore-worker@1
      command: journalctl -u pulpcore-worker@1
    - name: systemctl status pulpcore-worker@2
      command: systemctl status pulpcore-worker@2
    - name: journalctl -u pulpcore-worker@2ignore_errors
      command: journalctl -u pulpcore-worker@2ignore_errors
  become: true
  ignore_errors: true

- name: Fail
  fail:
    msg: pulp_installer failed on starting or restarting services. See debug output.
  become: true
