---
- name: Restart pulpcore service
  systemd:
    daemon_reload: true
    name: "pulpcore.service"
    state: restarted
  become: true
  retries: 5
  delay: 12
  register: result
  until: result is succeeded

- name: Delete symlink from old artifact directory location
  file:
    path: '{{ __pulp_old_artifact_dir }}'
    state: absent
  become: true
