---
- name: Install galaxy UI from source
  block:
    - name: Install NPM (distro-agnostic)
      package:
        name: npm
        state: present
      retries: "{{ pulp_devel_package_retries }}"
      register: result
      until: result is succeeded

    - name: Check if UI is installed
      stat:
        path: '{{ developer_user_home }}/devel/ansible-hub-ui'
      register: is_hub_installed

    - name: UI from devel path
      set_fact:
        hub_ui_path: '{{ is_hub_installed.stat.path }}'
      when: is_hub_installed.stat.exists

    - name: UI from git
      set_fact:
        hub_ui_path: '{{ pulp_user_home }}/ansible-hub-ui'
      when: not is_hub_installed.stat.exists

    - block:
        - name: Cloning Ansible Hub UI
          git:
            repo: 'https://github.com/ansible/ansible-hub-ui.git'
            dest: '{{ hub_ui_path }}'
            force: yes
            version: master
            update: yes
          register: ansible_hub_ui_git
          when: not is_hub_installed.stat.exists
          tags:
            - molecule-idempotence-notest

        - name: Install packages based on package.json
          npm:
            path: '{{ hub_ui_path }}'

        - name: Building Ansible Hub UI
          command: npm run build-standalone
          args:
            chdir: '{{ hub_ui_path }}'
          when:
            - is_hub_installed.stat.exists or ansible_hub_ui_git is defined
            - is_hub_installed.stat.exists or ansible_hub_ui_git.changed

        - name: Creates galaxy_ng static dir
          file:
            path: '{{ pulp_install_plugins["galaxy-ng"]["source_dir"] }}/galaxy_ng/app/static/galaxy_ng'
            state: directory

        - name: Copying Ansible Hub UI to galaxy_ng static dir
          copy:
            src: '{{ hub_ui_path }}/dist/'
            dest: '{{ pulp_install_plugins["galaxy-ng"]["source_dir"] }}/galaxy_ng/app/static/galaxy_ng'
            remote_src: yes
      become: yes
      become_user: '{{ pulp_user }}'


  when: __galaxy_ui_source is defined and __galaxy_ui_source == "source"

- name: Download galaxy ui from github
  command:
    cmd: python setup.py prepare_static --force-download-ui
    chdir: '{{ pulp_install_plugins["galaxy-ng"]["source_dir"] }}'
  when: __galaxy_ui_source is not defined or __galaxy_ui_source == "precompiled"
