---
- name: Install several useful packages (with workarounds)
  block:
    - name: Install several useful packages (distro-agnostic)
      package:
        name:
          - dstat
          - git
          - htop
          - iotop
          - jq
          - ncdu
          - tmux
          - tree
          - wget
          - curl
          - gnupg
          - npm
          - rsyslog
        state: present
      retries: "{{ pulp_devel_package_retries }}"
      register: result
      until: result is succeeded
  rescue:
    - name: Workaround the node.js temporary retirement
      yum:
        name:
          - https://kojipkgs.fedoraproject.org//packages/nodejs/16.13.2/2.el7/noarch/nodejs-docs-16.13.2-2.el7.noarch.rpm
          - https://kojipkgs.fedoraproject.org//packages/nodejs/16.13.2/2.el7/x86_64/nodejs-16.13.2-2.el7.x86_64.rpm
          - https://kojipkgs.fedoraproject.org//packages/nodejs/16.13.2/2.el7/x86_64/nodejs-full-i18n-16.13.2-2.el7.x86_64.rpm
          - https://kojipkgs.fedoraproject.org//packages/nodejs/16.13.2/2.el7/x86_64/nodejs-libs-16.13.2-2.el7.x86_64.rpm
          - https://kojipkgs.fedoraproject.org//packages/nodejs/16.13.2/2.el7/x86_64/npm-8.1.2-1.16.13.2.2.el7.x86_64.rpm
      when:
        - ansible_facts.os_family == 'RedHat'
        - ansible_facts.distribution_major_version|int == 7

    - name: Install several useful packages (distro-agnostic)
      package:
        name:
          - dstat
          - git
          - htop
          - iotop
          - jq
          - ncdu
          - tmux
          - tree
          - wget
          - curl
          - gnupg
          - npm
          - rsyslog
        state: present
      retries: "{{ pulp_devel_package_retries }}"
      register: result
      until: result is succeeded

- name: Install several useful packages (distro-specific)
  package:
    name: "{{ pulp_devel_distro_pkgs }}"
    state: present
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded

- name: Install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    state: present
    virtualenv: '{{ pulp_install_dir }}'
    virtualenv_command: '{{ pulp_python_interpreter }} -m venv'
  when:
    - (ansible_facts.distribution == 'CentOS') or (ansible_facts.distribution == 'RedHat')
    - ansible_facts.distribution_major_version|int == 8

- name: Create virtualenvwrapper symlink
  file:
    src: "{{ pulp_install_dir }}/bin/virtualenvwrapper.sh"
    dest: /usr/bin/virtualenvwrapper.sh
    state: link
  when:
    - (ansible_facts.distribution == 'CentOS') or (ansible_facts.distribution == 'RedHat')
    - ansible_facts.distribution_major_version|int == 8

- name: Install Minio Client
  get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin
    owner: '{{ developer_user }}'
    mode: 0750
  retries: "{{ pulp_devel_package_retries }}"
  register: result
  until: result is succeeded
...
