---
name: Galaxy CI
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'roles/galaxy_post_install/**'
      - 'roles/pulp_devel/tasks/galaxy_ui.yml'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 2 * * *'
jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Testing different python versions because of
      # https://pulp.plan.io/issues/5768#note-17
      matrix:
        include:
          - ansible_core: ansible-core
          - ansible_core: git+https://github.com/ansible/ansible.git
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Ansible
        run: |
          pip install --upgrade pip
          sudo apt remove ansible
          pip install ${{ matrix.ansible_core }}
      - name: Install Molecule
        run: pip install "molecule!=3.3.1" docker molecule-docker
      - name: Setting pulp.pulp_installer collection
        run: |
          make vendor
          make install
          ansible-galaxy collection install -p build/collections --force community.docker
      - name: Molecule Test
        run: |
          ansible --version
          cp .ci/assets/galaxy/group_vars/all molecule/source-static/group_vars/all
          rm -rf molecule/source-static/host_vars
          molecule test --scenario-name source-static
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        shell: bash
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Ansible
        run: |
          pip install --upgrade pip
          sudo apt remove ansible
          pip install ansible-core
      - name: Install Ansible-lint
        run: |
          pip install ansible-lint[yamllint]
      - name: Lint test
        run: |
          ansible-lint
